

# use PowerShell instead of sh:
# set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# hello:
#   Write-Host "Hello, world!"


# use cmd.exe instead of sh:
set shell := ["cmd.exe", "/c"]

juliapath := "d:/sys/ProgramsCopyInstalled/julia-1.11.1/bin/julia.exe"


[private]
default: julia


[doc("Open Julia REPL")]
[no-cd]
julia:
	{{juliapath}}


[doc("Execute Julia expression")]
[no-cd]
do *expr:
	{{juliapath}} -E {{expr}}


[doc("Execute Julia script file")]
[no-cd]
run filename:
	@{{juliapath}} {{filename}}


[doc("Generate a new AoC day project")]
[no-cd]
create day:
	{{juliapath}} {{justfile_directory()}}/generate_day.jl {{day}}

